#!/usr/bin/env python3
"""
自动从 jcnode.com 获取免费节点
流程：
  1. 抓取页面，提取视频链接
  2. 用 yt-dlp + cookies 下载音频（绕过 YouTube bot 检测）
  3. 用 Whisper 转录，提取口令
  4. POST 口令到 API，获取 v2ray 订阅链接
  5. 下载订阅内容写入 sub3.txt

GitHub Actions 使用说明：
  - 将 YouTube cookies（Netscape 格式）存入 Secret: YOUTUBE_COOKIES
  - workflow 会自动写入 /tmp/yt_cookies.txt 供 yt-dlp 使用
"""

import os
import re
import subprocess
import sys
import tempfile

import requests
from bs4 import BeautifulSoup

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SUB3_HOME = os.environ.get('SUB3_HOME')
SUB3_HOST = os.environ.get('SUB3_HOST')
SUB3_VERIFY = os.environ.get('SUB3_VERIFY')

# ──────────────────────────────────────────────
# 步骤 1：抓取页面，提取视频链接
# ──────────────────────────────────────────────
def fetch_video_url(page_url: str) -> str:
    print(f"\n[1] 正在访问页面：{page_url}")
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/124.0.0.0 Safari/537.36"
        )
    }
    resp = requests.get(page_url, headers=headers, timeout=30)
    resp.raise_for_status()

    soup = BeautifulSoup(resp.text, "html.parser")

    # 查找 <strong>本期视频（含今日口令）</strong> 后面的 <a>
    for strong in soup.find_all("strong"):
        if "本期视频" in strong.get_text() and "口令" in strong.get_text():
            parent = strong.parent
            a_tag = parent.find("a")
            if a_tag and a_tag.get("href"):
                video_url = a_tag["href"]
                print(f"[1] ✅ 找到视频链接：{video_url}")
                return video_url

    # 兜底：全页查找 YouTube 链接
    for a in soup.find_all("a", href=True):
        href = a["href"]
        if "youtu.be" in href or "youtube.com/watch" in href:
            print(f"[1] ✅ (兜底) 找到视频链接：{href}")
            return href

    raise RuntimeError("❌ 未能从页面找到视频链接，页面结构可能已变化。")


# ──────────────────────────────────────────────
# 步骤 2：下载视频音频（支持 cookies）
# ──────────────────────────────────────────────

def header_cookies_to_netscape(cookie_str: str, domain: str = ".youtube.com") -> str:
    """
    将 HTTP Header 格式的 cookies 字符串转换为 Netscape 格式。
    
    输入示例（GitHub Secret 中粘贴的内容）：
        PREF=f6=40000000; __Secure-3PAPISID=xxxx; GOOGLE_ABUSE_EXEMPTION=ID=xxx
    
    输出为 yt-dlp 可识别的 Netscape cookies 文件内容。
    """
    lines = ["# Netscape HTTP Cookie File", "# Generated by fetch_nodes.py", ""]
    for part in cookie_str.split(";"):
        part = part.strip()
        if not part or "=" not in part:
            continue
        name, _, value = part.partition("=")
        name  = name.strip()
        value = value.strip()
        # 字段：domain  include_subdomains  path  secure  expiry  name  value
        # secure 和 __Secure- 前缀的 cookie 标记为 TRUE
        secure = "TRUE" if name.startswith("__Secure-") or name.startswith("__Host-") else "FALSE"
        expiry = "2147483647"   # 远期过期（不影响实际有效性）
        lines.append(f"{domain}\tTRUE\t/\t{secure}\t{expiry}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


def is_netscape_format(content: str) -> bool:
    """判断 cookies 内容是否已经是 Netscape 格式"""
    for line in content.splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            # Netscape 格式每行有 7 个 tab 分隔字段
            return len(line.split("\t")) >= 6
    return False


def prepare_cookies_file(raw_content: str, out_path: str = "/tmp/yt_cookies.txt") -> str:
    """
    自动检测格式并转换，写入 Netscape 格式文件，返回文件路径。
    """
    raw_content = raw_content.strip()
    if is_netscape_format(raw_content):
        print("[2] 检测到 Netscape 格式 cookies，直接使用")
        netscape = raw_content
    else:
        print("[2] 检测到 Header 格式 cookies，自动转换为 Netscape 格式…")
        netscape = header_cookies_to_netscape(raw_content)
        # 打印转换后的行数（不打印内容，防止泄露）
        n = sum(1 for l in netscape.splitlines() if l and not l.startswith("#"))
        print(f"[2] 转换完成，共 {n} 条 cookie")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(netscape)
    return out_path


def get_cookies_file() -> str | None:
    """
    优先级：
      1. 环境变量 YOUTUBE_COOKIES_FILE（直接指定已有文件路径）
      2. 环境变量 YOUTUBE_COOKIES（cookies 文本，自动转换格式后写入文件）
      3. 默认路径 /tmp/yt_cookies.txt（由 workflow step 写入）
    两种 cookies 格式均支持：
      - Netscape 格式（# Netscape HTTP Cookie File 开头）
      - HTTP Header 格式（name=value; name2=value2 …）
    """
    # 方式 1：直接指定文件路径
    path = os.environ.get("YOUTUBE_COOKIES_FILE", "")
    if path and os.path.exists(path):
        content = open(path).read()
        if not is_netscape_format(content):
            print(f"[2] {path} 为 Header 格式，自动转换…")
            path = prepare_cookies_file(content)
        else:
            print(f"[2] 使用 cookies 文件：{path}")
        return path

    # 方式 2：环境变量内容
    content = os.environ.get("YOUTUBE_COOKIES", "")
    if content.strip():
        path = prepare_cookies_file(content)
        print(f"[2] cookies 已写入：{path}")
        return path

    # 方式 3：workflow 预写的默认路径
    default = "/tmp/yt_cookies.txt"
    if os.path.exists(default):
        content = open(default).read()
        if content.strip():
            if not is_netscape_format(content):
                print(f"[2] {default} 为 Header 格式，自动转换…")
                prepare_cookies_file(content, default)
            print(f"[2] 使用默认 cookies 文件：{default}")
            return default

    print("[2] ⚠️  未找到 cookies，将尝试无 cookies 下载（可能被 YouTube 拦截）")
    return None


def _base_cmd(video_url: str, output_path: str, cookies_file: str | None) -> list:
    """构建 yt-dlp 基础参数（不含格式选项）"""
    cmd = [
        "yt-dlp",
        "--no-playlist",
        "-o", f"{output_path}.%(ext)s",
        "--retries", "5",
        "--fragment-retries", "5",
        "--socket-timeout", "30",
        "--extractor-args", "youtube:player_client=android,web",
        "--no-warnings",
    ]
    if cookies_file:
        cmd += ["--cookies", cookies_file]
    cmd.append(video_url)
    return cmd


# 按优先级尝试的下载策略列表
# 每项：(描述, 额外参数)
DOWNLOAD_STRATEGIES = [
    # 策略1：最佳音频，不指定编码（让 yt-dlp 自由选择，再转 mp3）
    ("最佳音频→mp3",        ["-x", "--audio-format", "mp3"]),
    # 策略2：只取音频流，保留原始格式（m4a/webm/opus），不做转码
    ("最佳音频（原始格式）", ["-x"]),
    # 策略3：明确只要 m4a
    ("bestaudio[ext=m4a]",  ["-f", "bestaudio[ext=m4a]/bestaudio"]),
    # 策略4：bestaudio 无条件
    ("bestaudio",           ["-f", "bestaudio", "-x"]),
    # 策略5：最低质量音视频合并（兜底，会包含视频轨，只用音频部分）
    ("worst（兜底）",        ["-f", "worstvideo+worstaudio/worst", "-x"]),
]


def _run_ytdlp(cmd: list, label: str) -> subprocess.CompletedProcess:
    print(f"[2] 尝试策略「{label}」：{' '.join(cmd)}")
    return subprocess.run(cmd, capture_output=True, text=True, timeout=300)


def _find_output(output_path: str) -> str | None:
    for ext in ["mp3", "m4a", "webm", "opus", "ogg", "wav", "mp4"]:
        candidate = f"{output_path}.{ext}"
        if os.path.exists(candidate):
            return candidate
    # glob 兜底（yt-dlp 有时生成带额外后缀的文件名）
    import glob
    matches = glob.glob(f"{output_path}.*")
    return matches[0] if matches else None


def download_audio(video_url: str, output_path: str = "/tmp/jcnode_audio") -> str:
    print(f"\n[2] 正在下载音频：{video_url}")
    cookies_file = get_cookies_file()
    base = _base_cmd(video_url, output_path, cookies_file)

    last_stderr = ""
    for label, extra in DOWNLOAD_STRATEGIES:
        # 删掉上一次可能残留的文件
        import glob
        for f in glob.glob(f"{output_path}.*"):
            os.remove(f)

        # 把额外参数插到 url 之前（url 是最后一个元素）
        cmd = base[:-1] + extra + [base[-1]]
        result = _run_ytdlp(cmd, label)
        last_stderr = result.stderr

        if result.returncode == 0:
            found = _find_output(output_path)
            if found:
                size_kb = os.path.getsize(found) // 1024
                print(f"[2] ✅ 音频文件：{found}（{size_kb} KB）")
                return found

        # 致命错误：bot 检测，直接终止，不继续尝试
        if "Sign in to confirm" in result.stderr or \
           ("bot" in result.stderr.lower() and "ERROR" in result.stderr):
            raise RuntimeError(
                "❌ YouTube bot 检测拦截！\n"
                "请重新导出 YouTube cookies 并更新 GitHub Secret: YOUTUBE_COOKIES"
            )

        print(f"[2] 策略「{label}」失败，尝试下一个…\n    stderr: {result.stderr[-200:]}")

    raise RuntimeError(
        f"❌ 所有下载策略均失败，最后一次 stderr：\n{last_stderr[-600:]}"
    )


# ──────────────────────────────────────────────
# 步骤 3：语音转文字 → 提取口令
# ──────────────────────────────────────────────
def transcribe_audio(audio_path: str) -> str:
    print(f"\n[3] 正在转录音频（首次运行会下载 Whisper 模型 ~460 MB）…")
    import whisper

    model = whisper.load_model("small")
    result = model.transcribe(audio_path, language="zh", verbose=False)
    text = result["text"]
    print(f"[3] ✅ 转录完成，前300字：\n{text[:300]!r}")
    return text


def extract_code(text: str) -> str:
    patterns = [
        r"口令[：:\s「]?\s*([A-Za-z0-9\u4e00-\u9fff@#$%^&*!]{2,20})",
        r"密码[：:\s「]?\s*([A-Za-z0-9\u4e00-\u9fff@#$%^&*!]{2,20})",
        r"暗号[：:\s「]?\s*([A-Za-z0-9\u4e00-\u9fff@#$%^&*!]{2,20})",
    ]
    for pat in patterns:
        m = re.search(pat, text)
        if m:
            code = m.group(1).strip()
            print(f"[3] ✅ 识别到口令：{code!r}")
            return code

    raise RuntimeError(
        f"❌ 未能从转录文字中识别口令。\n"
        f"完整转录内容：\n{text}"
    )


# ──────────────────────────────────────────────
# 步骤 4：提交口令，解析节点链接
# ──────────────────────────────────────────────
def verify_code(code: str) -> dict:
    print(f"\n[4] 正在提交口令到 …")
    headers = {
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0",
        "Referer": SUB3_HOST,
    }
    resp = requests.post(SUB3_VERIFY, json={"code": code}, headers=headers, timeout=30)
    resp.raise_for_status()
    data = resp.json()
    print(f"[4] 接口响应：{data}")
    if not data.get("success"):
        raise RuntimeError(f"❌ 口令验证失败：{data}")
    return data


def get_v2ray_url(api_data: dict) -> str:
    try:
        url = api_data["links"]["proxy"]["v2ray"]
        print(f"[4] ✅ v2ray 订阅链接：{url}")
        return url
    except KeyError as e:
        raise RuntimeError(
            f"❌ 响应结构异常，找不到 proxy.v2ray 字段：{e}\n数据：{api_data}"
        )


# ──────────────────────────────────────────────
# 步骤 5：下载订阅内容，写入 sub3.txt
# ──────────────────────────────────────────────
def download_sub(v2ray_url: str, output_file: str = "sub3.txt") -> None:
    print(f"\n[5] 正在下载订阅内容：{v2ray_url}")
    headers = {"User-Agent": "ClashMeta/1.0"}
    resp = requests.get(v2ray_url, headers=headers, timeout=30)
    resp.raise_for_status()
    content = resp.text

    out_path = os.path.join(SCRIPT_DIR, output_file)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)

    lines = content.strip().splitlines()
    print(f"[5] ✅ 已写入 {out_path}（{len(lines)} 行，{len(content)} 字节）")


# ──────────────────────────────────────────────
# 主流程
# ──────────────────────────────────────────────
def main():

    video_url = fetch_video_url(SUB3_HOME)
    audio_path = download_audio(video_url)
    text       = transcribe_audio(audio_path)
    code       = extract_code(text)
    api_data   = verify_code(code)
    v2ray_url  = get_v2ray_url(api_data)
    download_sub(v2ray_url)

    print("\n✅ 全部完成！订阅内容已保存到 sub3.txt")


if __name__ == "__main__":
    main()    